$(function(){
	var options = {
		url:'list.json',
		skin:'#3c4b52',
		treeData:[
            {
                "id": 165,
                "systemId": 24,
                "pid": 0,
                "name": "GS服务中心",
                "url": "#",
                "target": "8",
                "orders": 8,
                "version": 0,
                "icon": null,
                "childMenus": [
                    {
                        "id": 166,
                        "systemId": 24,
                        "pid": 165,
                        "name": "系统管理",
                        "icon": null,
                        "url": "#",
                        "target": "8_1",
                        "orders": 1,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 167,
                                "systemId": 24,
                                "pid": 166,
                                "name": "GS客服组",
                                "icon": null,
                                "url": "/common/404.jsp",
                                "target": "8_1_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 168,
                                "systemId": 24,
                                "pid": 166,
                                "name": "GS成员",
                                "icon": null,
                                "url": "/gsCustomer/index",
                                "target": "8_1_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 169,
                                "systemId": 24,
                                "pid": 166,
                                "name": "国家管理",
                                "icon": null,
                                "url": "/gsCountryManager/index",
                                "target": "8_1_3",
                                "orders": 3,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 170,
                                "systemId": 24,
                                "pid": 166,
                                "name": "活动类型管理",
                                "icon": null,
                                "url": "/gsActiveType/index",
                                "target": "8_1_4",
                                "orders": 4,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 171,
                                "systemId": 24,
                                "pid": 166,
                                "name": "活动管理",
                                "icon": null,
                                "url": "/gsActive/index",
                                "target": "8_1_5",
                                "orders": 5,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    },
                    {
                        "id": 172,
                        "systemId": 24,
                        "pid": 165,
                        "name": "基础数据",
                        "icon": null,
                        "url": "#",
                        "target": "8_2",
                        "orders": 2,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 173,
                                "systemId": 24,
                                "pid": 172,
                                "name": "个人列表",
                                "icon": null,
                                "url": "/gsUserInfoList/index",
                                "target": "8_2_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 174,
                                "systemId": 24,
                                "pid": 172,
                                "name": "交易列表",
                                "icon": null,
                                "url": "/gsTradeList/index",
                                "target": "8_2_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 175,
                                "systemId": 24,
                                "pid": 172,
                                "name": "国家列表",
                                "icon": null,
                                "url": "/gsCountryInfo/index",
                                "target": "8_2_3",
                                "orders": 3,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 176,
                                "systemId": 24,
                                "pid": 172,
                                "name": "家族列表",
                                "icon": null,
                                "url": "/gsFamilyList/index",
                                "target": "8_2_4",
                                "orders": 4,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 177,
                                "systemId": 24,
                                "pid": 172,
                                "name": "活动参与人数",
                                "icon": null,
                                "url": "/gsActiveList/index",
                                "target": "8_2_5",
                                "orders": 5,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    },
                    {
                        "id": 178,
                        "systemId": 24,
                        "pid": 165,
                        "name": "报表数据",
                        "icon": null,
                        "url": "#",
                        "target": "8_3",
                        "orders": 3,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 179,
                                "systemId": 24,
                                "pid": 178,
                                "name": "后台数据",
                                "icon": null,
                                "url": "/gsCountryData/backgroundIndex",
                                "target": "8_3_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 180,
                                "systemId": 24,
                                "pid": 178,
                                "name": "区服对比",
                                "icon": null,
                                "url": "/gsCountryData/contrastIndex",
                                "target": "8_3_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 181,
                                "systemId": 24,
                                "pid": 178,
                                "name": "区服统计",
                                "icon": null,
                                "url": "/gsCountryData/statisticIndex",
                                "target": "8_3_3",
                                "orders": 3,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    }
                ]
            },
            {
                "id": 157,
                "systemId": 24,
                "pid": 0,
                "name": "客服助手",
                "url": "#",
                "target": "7",
                "orders": 7,
                "version": 0,
                "icon": null,
                "childMenus": [
                    {
                        "id": 158,
                        "systemId": 24,
                        "pid": 157,
                        "name": "充值订单查询（历史）",
                        "icon": null,
                        "url": "/playerData/rechargeOrder/index",
                        "target": "7_1",
                        "orders": 1,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 159,
                        "systemId": 24,
                        "pid": 157,
                        "name": "SDK订单查询",
                        "icon": null,
                        "url": "/playerData/sdkOrder/index",
                        "target": "7_2",
                        "orders": 2,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 160,
                        "systemId": 24,
                        "pid": 157,
                        "name": "玩家行为数据",
                        "icon": null,
                        "url": "/playerData/playerBehavior/index",
                        "target": "7_3",
                        "orders": 3,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 161,
                        "systemId": 24,
                        "pid": 157,
                        "name": "玩家查询",
                        "icon": null,
                        "url": "/playerData/playerQuery/index",
                        "target": "7_4",
                        "orders": 4,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 162,
                        "systemId": 24,
                        "pid": 157,
                        "name": "战斗数据",
                        "icon": null,
                        "url": "/playerData/CombatData/index",
                        "target": "7_5",
                        "orders": 5,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 163,
                        "systemId": 24,
                        "pid": 157,
                        "name": "玩家信息查询",
                        "icon": null,
                        "url": "/playerData/playerInfoData/index",
                        "target": "7_6",
                        "orders": 6,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 164,
                        "systemId": 24,
                        "pid": 157,
                        "name": "任务列表",
                        "icon": null,
                        "url": "/playerData/taskList/index",
                        "target": "7_7",
                        "orders": 7,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": []
                    }
                ]
            },
            {
                "id": 154,
                "systemId": 24,
                "pid": 0,
                "name": "市场分析",
                "url": "#",
                "target": "6",
                "orders": 6,
                "version": 0,
                "icon": null,
                "childMenus": [
                    {
                        "id": 155,
                        "systemId": 24,
                        "pid": 154,
                        "name": "竞品列表",
                        "icon": null,
                        "url": "/common/index?jspPath=dev_assistant/channel_games_table",
                        "target": "6_1",
                        "orders": 1,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 156,
                        "systemId": 24,
                        "pid": 154,
                        "name": "竞品分析",
                        "icon": null,
                        "url": "/common/index?jspPath=dev_assistant/channel_games_echarts",
                        "target": "6_2",
                        "orders": 2,
                        "addTime": "2019-06-04T07:50:35.000+0000",
                        "updateTime": "2019-06-04T07:50:35.000+0000",
                        "version": 0,
                        "childMenus": []
                    }
                ]
            },
            {
                "id": 138,
                "systemId": 24,
                "pid": 0,
                "name": "广告监控",
                "url": "#",
                "target": "5",
                "orders": 5,
                "version": 0,
                "icon": null,
                "childMenus": [
                    {
                        "id": 139,
                        "systemId": 24,
                        "pid": 138,
                        "name": "广告概览",
                        "icon": null,
                        "url": "/advertPromotionOverView/index",
                        "target": "5_1",
                        "orders": 1,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 140,
                        "systemId": 24,
                        "pid": 138,
                        "name": "官网分包数据",
                        "icon": null,
                        "url": "/subContractData/realTimeChannel",
                        "target": "5_2",
                        "orders": 2,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 141,
                        "systemId": 24,
                        "pid": 138,
                        "name": "产品设置",
                        "icon": null,
                        "url": "#",
                        "target": "5_3",
                        "orders": 3,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 142,
                                "systemId": 24,
                                "pid": 141,
                                "name": "渠道管理",
                                "icon": null,
                                "url": "/advertChannel/index",
                                "target": "5_3_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 143,
                                "systemId": 24,
                                "pid": 141,
                                "name": "广告管理",
                                "icon": null,
                                "url": "/advertPromotion/index",
                                "target": "5_3_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 144,
                                "systemId": 24,
                                "pid": 141,
                                "name": "广告组管理",
                                "icon": null,
                                "url": "/advertPromotionGroup/index",
                                "target": "5_3_3",
                                "orders": 3,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 145,
                                "systemId": 24,
                                "pid": 141,
                                "name": "白名单管理",
                                "icon": null,
                                "url": "/advertWhiteList/index",
                                "target": "5_3_4",
                                "orders": 4,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    },
                    {
                        "id": 146,
                        "systemId": 24,
                        "pid": 138,
                        "name": "推广广告",
                        "icon": null,
                        "url": "/advertPromotion/promotionActivitiesIndexNew",
                        "target": "5_4",
                        "orders": 4,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 147,
                        "systemId": 24,
                        "pid": 138,
                        "name": "广告分析",
                        "icon": null,
                        "url": "/clusteringAnalysis/index",
                        "target": "5_5",
                        "orders": 5,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 148,
                        "systemId": 24,
                        "pid": 138,
                        "name": "有玩网络",
                        "icon": null,
                        "url": "#",
                        "target": "5_6",
                        "orders": 6,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 149,
                                "systemId": 24,
                                "pid": 148,
                                "name": "广告登录留存",
                                "icon": null,
                                "url": "/common/index?jspPath=/advert_monitor/youwan/day_login",
                                "target": "5_6_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 150,
                                "systemId": 24,
                                "pid": 148,
                                "name": "广告效果（按天）",
                                "icon": null,
                                "url": "/common/index?jspPath=/advert_monitor/youwan/day_effect",
                                "target": "5_6_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 151,
                                "systemId": 24,
                                "pid": 148,
                                "name": "广告效果（按时）",
                                "icon": null,
                                "url": "/common/index?jspPath=/advert_monitor/youwan/hour_effect",
                                "target": "5_6_3",
                                "orders": 3,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 152,
                                "systemId": 24,
                                "pid": 148,
                                "name": "广告首充留存",
                                "icon": null,
                                "url": "/common/index?jspPath=/advert_monitor/youwan/pay_login",
                                "target": "5_6_4",
                                "orders": 4,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 153,
                                "systemId": 24,
                                "pid": 148,
                                "name": "每日LTV",
                                "icon": null,
                                "url": "/common/index?jspPath=/advert_monitor/youwan/day_ltv",
                                "target": "5_6_5",
                                "orders": 5,
                                "addTime": "2019-06-04T07:50:35.000+0000",
                                "updateTime": "2019-06-04T07:50:35.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    }
                ]
            },
            {
                "id": 136,
                "systemId": 24,
                "pid": 0,
                "name": "应用管理",
                "url": "#",
                "target": "4",
                "orders": 4,
                "version": 0,
                "icon": null,
                "childMenus": [
                    {
                        "id": 137,
                        "systemId": 24,
                        "pid": 136,
                        "name": "基本信息",
                        "icon": null,
                        "url": "/sasProduct/updateView",
                        "target": "4_1",
                        "orders": 1,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    }
                ]
            },
            {
                "id": 123,
                "systemId": 24,
                "pid": 0,
                "name": "运营助手",
                "url": "#",
                "target": "3",
                "orders": 3,
                "version": 0,
                "icon": null,
                "childMenus": [
                    {
                        "id": 124,
                        "systemId": 24,
                        "pid": 123,
                        "name": "事件管理",
                        "icon": null,
                        "url": "/sasEvent/index",
                        "target": "3_1",
                        "orders": 1,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 125,
                        "systemId": 24,
                        "pid": 123,
                        "name": "渠道管理",
                        "icon": null,
                        "url": "/sasChannel/index",
                        "target": "3_2",
                        "orders": 2,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 126,
                        "systemId": 24,
                        "pid": 123,
                        "name": "区服管理",
                        "icon": null,
                        "url": "/sasServer/index",
                        "target": "3_3",
                        "orders": 3,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 127,
                        "systemId": 24,
                        "pid": 123,
                        "name": "虚拟币管理",
                        "icon": null,
                        "url": "/sasMoneyType/index",
                        "target": "3_4",
                        "orders": 4,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 128,
                        "systemId": 24,
                        "pid": 123,
                        "name": "代币原因管理",
                        "icon": null,
                        "url": "/sasReason/index",
                        "target": "3_5",
                        "orders": 5,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 129,
                        "systemId": 24,
                        "pid": 123,
                        "name": "物品原因管理",
                        "icon": null,
                        "url": "/sasItemReason/index",
                        "target": "3_6",
                        "orders": 6,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 130,
                        "systemId": 24,
                        "pid": 123,
                        "name": "物品类型",
                        "icon": null,
                        "url": "/sasMateriaType/index",
                        "target": "3_7",
                        "orders": 7,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 131,
                        "systemId": 24,
                        "pid": 123,
                        "name": "物品管理",
                        "icon": null,
                        "url": "/sasMateriaItem/index",
                        "target": "3_8",
                        "orders": 8,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 132,
                        "systemId": 24,
                        "pid": 123,
                        "name": "商店物品管理",
                        "icon": null,
                        "url": "/sasShopType/index",
                        "target": "3_9",
                        "orders": 9,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 133,
                        "systemId": 24,
                        "pid": 123,
                        "name": "渠道开服设置",
                        "icon": null,
                        "url": "/sasChannelOpenTime/index",
                        "target": "3_10",
                        "orders": 10,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 134,
                        "systemId": 24,
                        "pid": 123,
                        "name": "充值档位类型",
                        "icon": null,
                        "url": "/sasGearType/index",
                        "target": "3_11",
                        "orders": 11,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 135,
                        "systemId": 24,
                        "pid": 123,
                        "name": "充值档位",
                        "icon": null,
                        "url": "/sasGear/index",
                        "target": "3_12",
                        "orders": 12,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": []
                    }
                ]
            },
            {
                "id": 182,
                "systemId": 24,
                "pid": 0,
                "name": "开发助手",
                "url": "#",
                "target": "2",
                "orders": 2,
                "version": 0,
                "icon": null,
                "childMenus": [
                    {
                        "id": 183,
                        "systemId": 24,
                        "pid": 182,
                        "name": "日志查看",
                        "icon": null,
                        "url": "/logView/index",
                        "target": "2_1",
                        "orders": 1,
                        "addTime": "2019-06-04T07:52:17.000+0000",
                        "updateTime": "2019-06-04T07:52:17.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 184,
                        "systemId": 24,
                        "pid": 182,
                        "name": "日志面板",
                        "icon": null,
                        "url": "/logPanel/index",
                        "target": "2_2",
                        "orders": 2,
                        "addTime": "2019-06-04T07:52:17.000+0000",
                        "updateTime": "2019-06-04T07:52:17.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 185,
                        "systemId": 24,
                        "pid": 182,
                        "name": "错误分析",
                        "icon": null,
                        "url": "/page/dev_assistant/dev_assistant_1.jsp",
                        "target": "2_3",
                        "orders": 3,
                        "addTime": "2019-06-04T07:52:17.000+0000",
                        "updateTime": "2019-06-04T07:52:17.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 186,
                        "systemId": 24,
                        "pid": 182,
                        "name": "错误列表",
                        "icon": null,
                        "url": "/page/dev_assistant/dev_assistant_2.jsp",
                        "target": "2_4",
                        "orders": 4,
                        "addTime": "2019-06-04T07:52:17.000+0000",
                        "updateTime": "2019-06-04T07:52:17.000+0000",
                        "version": 0,
                        "childMenus": []
                    },
                    {
                        "id": 187,
                        "systemId": 24,
                        "pid": 182,
                        "name": "接入文档",
                        "icon": null,
                        "url": "/common/index?jspPath=/wikitem/wikiTem",
                        "target": "2_5",
                        "orders": 5,
                        "addTime": "2019-06-04T07:52:17.000+0000",
                        "updateTime": "2019-06-04T07:52:17.000+0000",
                        "version": 0,
                        "childMenus": []
                    }
                ]
            },
            {
                "id": 84,
                "systemId": 24,
                "pid": 0,
                "name": "数据分析",
                "url": "#",
                "target": "1",
                "orders": 1,
                "version": 0,
                "icon": null,
                "childMenus": [
                    {
                        "id": 85,
                        "systemId": 24,
                        "pid": 84,
                        "name": "数据概览",
                        "icon": null,
                        "url": "#",
                        "target": "1_1",
                        "orders": 1,
                        "addTime": "2019-06-04T07:50:33.000+0000",
                        "updateTime": "2019-06-04T07:50:33.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 86,
                                "systemId": 24,
                                "pid": 85,
                                "name": "游戏概览",
                                "icon": null,
                                "url": "/gameOverView/index_new",
                                "target": "1_1_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 87,
                                "systemId": 24,
                                "pid": 85,
                                "name": "日报",
                                "icon": null,
                                "url": "/dailydata/index",
                                "target": "1_1_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 88,
                                "systemId": 24,
                                "pid": 85,
                                "name": "周报",
                                "icon": null,
                                "url": "/weekly/view",
                                "target": "1_1_3",
                                "orders": 3,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 89,
                                "systemId": 24,
                                "pid": 85,
                                "name": "月报",
                                "icon": null,
                                "url": "/monthly/index",
                                "target": "1_1_4",
                                "orders": 4,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    },
                    {
                        "id": 90,
                        "systemId": 24,
                        "pid": 84,
                        "name": "实时数据",
                        "icon": null,
                        "url": "#",
                        "target": "1_2",
                        "orders": 2,
                        "addTime": "2019-06-04T07:50:33.000+0000",
                        "updateTime": "2019-06-04T07:50:33.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 91,
                                "systemId": 24,
                                "pid": 90,
                                "name": "实时数据",
                                "icon": null,
                                "url": "/realTime/view/v1",
                                "target": "1_2_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 92,
                                "systemId": 24,
                                "pid": 90,
                                "name": "实时留存",
                                "icon": null,
                                "url": "/common/index?jspPath=/apply_analysis/data_overview/realtimeKeep",
                                "target": "1_2_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 93,
                                "systemId": 24,
                                "pid": 90,
                                "name": "实时分渠道分区服",
                                "icon": null,
                                "url": "/common/index?jspPath=/apply_analysis/data_overview/realtimeChannel",
                                "target": "1_2_3",
                                "orders": 3,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    },
                    {
                        "id": 94,
                        "systemId": 24,
                        "pid": 84,
                        "name": "游戏玩家",
                        "icon": null,
                        "url": "#",
                        "target": "1_3",
                        "orders": 3,
                        "addTime": "2019-06-04T07:50:33.000+0000",
                        "updateTime": "2019-06-04T07:50:33.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 95,
                                "systemId": 24,
                                "pid": 94,
                                "name": "新增玩家",
                                "icon": null,
                                "url": "/newPlayer/index",
                                "target": "1_3_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 96,
                                "systemId": 24,
                                "pid": 94,
                                "name": "活跃玩家",
                                "icon": null,
                                "url": "/actPlayer/index",
                                "target": "1_3_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 97,
                                "systemId": 24,
                                "pid": 94,
                                "name": "玩家留存",
                                "icon": null,
                                "url": "/playerRemain/index",
                                "target": "1_3_3",
                                "orders": 3,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 98,
                                "systemId": 24,
                                "pid": 94,
                                "name": "付费转化",
                                "icon": null,
                                "url": "/common/index?jspPath=/apply_analysis/gamer/pay_conversion",
                                "target": "1_3_4",
                                "orders": 4,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 99,
                                "systemId": 24,
                                "pid": 94,
                                "name": "玩家流失",
                                "icon": null,
                                "url": "/userLost/index",
                                "target": "1_3_5",
                                "orders": 5,
                                "addTime": "2019-06-04T07:50:33.000+0000",
                                "updateTime": "2019-06-04T07:50:33.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 100,
                                "systemId": 24,
                                "pid": 94,
                                "name": "设备相关",
                                "icon": null,
                                "url": "/device/index",
                                "target": "1_3_6",
                                "orders": 6,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    },
                    {
                        "id": 101,
                        "systemId": 24,
                        "pid": 84,
                        "name": "收入分析",
                        "icon": null,
                        "url": "#",
                        "target": "1_4",
                        "orders": 4,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 102,
                                "systemId": 24,
                                "pid": 101,
                                "name": "收入数据",
                                "icon": null,
                                "url": "/common/index?jspPath=/apply_analysis/income_analysis/income_data",
                                "target": "1_4_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 103,
                                "systemId": 24,
                                "pid": 101,
                                "name": "付费渗透",
                                "icon": null,
                                "url": "/common/index?jspPath=/apply_analysis/income_analysis/pay_penetration",
                                "target": "1_4_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 104,
                                "systemId": 24,
                                "pid": 101,
                                "name": "新玩家价值",
                                "icon": null,
                                "url": "/newPlayerValue/index",
                                "target": "1_4_3",
                                "orders": 3,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 105,
                                "systemId": 24,
                                "pid": 101,
                                "name": "付费习惯",
                                "icon": null,
                                "url": "/chargeData/paymentHabitIndex",
                                "target": "1_4_4",
                                "orders": 4,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    },
                    {
                        "id": 106,
                        "systemId": 24,
                        "pid": 84,
                        "name": "虚拟消费",
                        "icon": null,
                        "url": "#",
                        "target": "1_5",
                        "orders": 5,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 107,
                                "systemId": 24,
                                "pid": 106,
                                "name": "虚拟币",
                                "icon": null,
                                "url": "/common/index?jspPath=/apply_analysis/virtual_consumption/virtual_currency",
                                "target": "1_5_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 108,
                                "systemId": 24,
                                "pid": 106,
                                "name": "消费喜好",
                                "icon": null,
                                "url": "/consumerLove/index",
                                "target": "1_5_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 109,
                                "systemId": 24,
                                "pid": 106,
                                "name": "商城购买",
                                "icon": null,
                                "url": "/shopBuy/index",
                                "target": "1_5_3",
                                "orders": 3,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    },
                    {
                        "id": 110,
                        "systemId": 24,
                        "pid": 84,
                        "name": "等级分析",
                        "icon": null,
                        "url": "#",
                        "target": "1_6",
                        "orders": 6,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 111,
                                "systemId": 24,
                                "pid": 110,
                                "name": "等级详情",
                                "icon": null,
                                "url": "/rankDetail/index",
                                "target": "1_6_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    },
                    {
                        "id": 112,
                        "systemId": 24,
                        "pid": 84,
                        "name": "行为分析",
                        "icon": null,
                        "url": "#",
                        "target": "1_7",
                        "orders": 7,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 113,
                                "systemId": 24,
                                "pid": 112,
                                "name": "事件分析",
                                "icon": null,
                                "url": "/eventAnalysis/index",
                                "target": "1_7_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            },
                            {
                                "id": 114,
                                "systemId": 24,
                                "pid": 112,
                                "name": "拍卖行",
                                "icon": null,
                                "url": "/customAuction/index",
                                "target": "1_7_2",
                                "orders": 2,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    },
                    {
                        "id": 115,
                        "systemId": 24,
                        "pid": 84,
                        "name": "物品产销",
                        "icon": null,
                        "url": "#",
                        "target": "1_8",
                        "orders": 8,
                        "addTime": "2019-06-04T07:50:34.000+0000",
                        "updateTime": "2019-06-04T07:50:34.000+0000",
                        "version": 0,
                        "childMenus": [
                            {
                                "id": 116,
                                "systemId": 24,
                                "pid": 115,
                                "name": "物品产销",
                                "icon": null,
                                "url": "/goodsMarket/index",
                                "target": "1_8_1",
                                "orders": 1,
                                "addTime": "2019-06-04T07:50:34.000+0000",
                                "updateTime": "2019-06-04T07:50:34.000+0000",
                                "version": 0,
                                "childMenus": []
                            }
                        ]
                    }
                ]
            }
        ]
	}
	var myTree = $('#myTree').menuTree(options);
	$('#getCheckIds').click(function(){
		$('div.logs').html('获取ids:<br/>'+myTree.getCheckIdStr());
	})
	$('#getCheckData').click(function(){
		$('div.logs').html('获取数据:<br/>'+myTree.getCheckData());
	})
})